image: registry.usm.su.univ-lorraine.fr:5050/packages/ci-cd/aupkg/psmodule:1.3.0

stages:
  - build
  - mirror

build:
  tags:
    - docker
  stage: build
  script:
    - choco -v
    - pwsh -Command Get-Module -ListAvailable
    - pwsh -Command Import-Module -Name AU
    - pwsh -File ./update_all.ps1
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"

mirror_to_github:
  tags:
    - docker
  stage: mirror
  variables:
    GIT_DEPTH: "0"
  before_script:
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
  script:
    - |
      if [ -z "$CI_GITHUB_REPO" ] || [ -z "$CI_GITHUB_APIKEY" ]; then
        echo "Variables CI_GITHUB_REPO et/ou CI_GITHUB_APIKEY manquantes"; exit 1; fi
    - git remote remove github || true
    - git remote add github "https://${CI_GITHUB_USERNAME:-x-access-token}:${CI_GITHUB_APIKEY}@github.com/${CI_GITHUB_REPO}.git"
    - git fetch --tags origin
    - git push --mirror github
  needs:
    - job: build
      optional: true